// export const vendorsData = [
//   { name: "Orbita", status: "active", label: "Orbita" },
//   { name: "Kant", status: "active", label: "Kant" },
//   { name: "Diplomat", status: "active", label: "Diplomat" },
//   { name: "Orbita5", status: "active", label: "Orbita5" },
//   { name: "Magako", status: "active", label: "Magako" },
//   { name: "Vest Inv", status: "active", label: "Vest Inv." },
//   { name: "Svaneti", status: "active", label: "Svaneti" },
//   { name: "Orbita1", status: "active", label: "Orbita1" },
//   { name: "Orbita2", status: "inactive", label: "Orbita2" },
//   { name: "Diplomat1", status: "inactive", label: "Diplomat1" },
//   { name: "Orbita3", status: "inactive", label: "Orbita3" },
//   { name: "Vest Inv1", status: "inactive", label: "Vest Inv1." },
//   { name: "Orbita4", status: "inactive", label: "Orbita4" },
//   { name: "Orbita6", status: "inactive", label: "Orbita6" },
//   { name: "Kant1", status: "inactive", label: "Kant1" },
//   { name: "Orbita7", status: "inactive", label: "Orbita7" },
//   { name: "Magako1", status: "inactive", label: "Magako1" },
//   { name: "Svaneti1", status: "inactive", label: "Svaneti1" },
// ];
export const vendorsData = [
  { name: "მომწოდებელი 1", status: "active", label: "Orbita" },
  { name: "მომწოდებელი 2", status: "active", label: "Kant" },
  { name: "მომწოდებელი 3", status: "active", label: "Diplomat" },
  { name: "მომწოდებელი 4", status: "active", label: "Orbita5" },
  { name: "მომწოდებელი 5", status: "active", label: "Magako" },
  { name: "მომწოდებელი 6", status: "active", label: "Vest Inv." },
  { name: "მომწოდებელი 7", status: "active", label: "Svaneti" },
  { name: "მომწოდებელი 8", status: "active", label: "Orbita1" },
  { name: "მომწოდებელი 9", status: "inactive", label: "Orbita2" },
  { name: "მომწოდებელი 10", status: "inactive", label: "Diplomat1" },
  { name: "მომწოდებელი 11", status: "inactive", label: "Orbita3" },
  { name: "მომწოდებელი 12", status: "inactive", label: "Vest Inv1." },
  { name: "მომწოდებელი 13", status: "inactive", label: "Orbita4" },
  { name: "მომწოდებელი 14", status: "inactive", label: "Orbita6" },
  { name: "მომწოდებელი 15", status: "inactive", label: "Kant1" },
  { name: "მომწოდებელი 16", status: "inactive", label: "Orbita7" },
  { name: "მომწოდებელი 17", status: "inactive", label: "Magako1" },
  { name: "მომწოდებელი 18", status: "inactive", label: "Svaneti1" },
];
